version: 2.1

executors:
  macos-executor:
    macos:
      xcode: 15.4.0
    working_directory: ~/project

jobs:
  test:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: List Project Files
          command: ls -R ~/project
      - run:
          name: Run Xcode Tests
          command: |
            xcodebuild clean build test \
              -project EssentialFeed/EssentialFeed.xcodeproj \
              -scheme "CI" \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO

workflows:
  test-only:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
