version: 2.1

executors:
  macos-executor:
    macos:
      xcode: 15.4.0  # Specify the Xcode version you're using
    working_directory: ~/project

jobs:
  test:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Run Xcode Tests
          command: |
            xcodebuild clean build test \
              -project EssentialFeed/EssentialFeed.xcodeproj \  # Your project path
              -scheme "CI" \                                    # Your scheme
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO

workflows:
  test-only:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main  # Only run on push to 'main'
